---
- name: Setup benign data scripts on Akamai API Security Node
  hosts: akamai
  become: true

  tasks:

    - name: Upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Install python3-pip package
      ansible.builtin.yum:
        name: python3-pip
        state: latest

    - name: Extract wwt-lab-files.zip in the labuser folder
      ansible.builtin.unarchive:
        src: /home/labuser/Ansible/API_Sec_Lab/files/wwt-lab-files.zip
        dest: /home/labuser/
        creates: /home/labuser/wwt-lab-files/

#    - name: Install specified python requirements
#      ansible.builtin.pip:
#        requirements: /home/labuser/wwt-lab-files/requirements.txt

    - name: Copy and Execute the script 
      #chdir: /home/labuser/wwt-lab-files/ 
      ansible.builtin.copy:
        src: /home/labuser/Ansible/API_Sec_Lab/files/benign-data.sh
        dest: /home/labuser/wwt-lab-files/benign-data.sh
        owner: labuser
        group: labuser
        mode: '0774'